### ISSUE TITLE
training config file of ViT-Base/16 for plot-loop?

### ISSUE THREAD

**Issue by yuzhou914** [CHENGY12/PLOT#1]
Very impressive work! Do you have the training config file of ViT-Base/16 for plot-loop?

**Comment by CHENGY12** [comment]
Thanks very much for your attention.  The current version does not support ViT-based encoders, since the training of OT distance needs discriminative initialized local visual features.  For this issue, we have an extended version PLOT++.   Will release PLOT++ in 3 weeks.  If you want to obtain it early, please free free to drop me an email.

**Comment by CHENGY12** [comment]
The extension of PLOT (PLOT++) to support ViT-based backbones is released, which includes the training/testing configs and our trained models. Please refer to [PLOT++](https://github.com/CHENGY12/PLOT/tree/main/plot-pp) for details.
