### ISSUE TITLE
Does the code PLOT-CoOp support the ViT backbone? and How to run this code on multiple GPUs?

### ISSUE THREAD

**Issue by jingzhengli** [CHENGY12/PLOT#7]
1) Does the code PLOT-CoOP support the ViT backbone? I run the **PLOT-CoOp code with ViT backbone**, it occurs an error. 
2) I have 4 nvidia A100 GPUs. When I run the code, it occurs an error with "out of memory". I want to know if this code support multiple GPUs.

**Comment by CHENGY12** [comment]
Hi Jingzheng,  PLOT-CoOp can be used for the ViT backbone.  But it requires the modification of the ViT network, such as     [using all tokens instead of a single class token](https://github.com/CHENGY12/PLOT/blob/main/plot-coop/clip/model.py#L93). We use the same operation for the ResNet-based model. 

It supports training on multiple GPUs. The training of ImageNet relies on multiple GPUs. Could you please check if the 
GPUs are occupied by other jobs?
